name: tides-ts-pyTMD
channels:
  - conda-forge
dependencies:
  - pip
  - pyyaml
  - numpy
  - rasterio
  - matplotlib
  - cartopy
  - pandas
  - geopandas
  - jupyter
  - netcdf4
  - pytmd
  - fiona
  - shapely
  - flake8