#model: CATS2008  # Model Name
#path: /Volumes/Extreme Pro/cats2008_tmd    # Absolute Path to Model's data directory
#model: 'AOTIM5'  # Model Name
#path: '/Volumes/Extreme Pro/aotim5_tmd/data'    # Absolute Path to Model's data directory
model: 'FES2014'  # Model Name
path: '/Volumes/Extreme Pro/AVISO'    # Absolute Path to Model's data directory
out_path: /Users/enricociraci/Desktop      # Absolute Path to Output directory
out_format: netcdf      # ascii/txt/netcdf
date1: 01/01/2008         # Initial Date MM/DD/YYYY
date2: 01/10/2008         # Final Date MM/DD/YYYY