name: preliminary-ci-test-with-mambaforge

on:
  push:
    branches: [ dev ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually


jobs:
  build-os:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.7", "3.8", "3.9" ]

    name: ci-test+cache
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2  # checkout repository

      - name: Set cache date  # activate cache
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
#
      - name: Setup Mambaforge  # setup environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-test
          channel-priority: strict
          environment-file: environment.yml
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
#
#      - name: Update environment
#        run: mamba env update -n env-test -f environment.yml
#        if: steps.cache.outputs.cache-hit != 'true'