name: preliminary-ci-test-with-mambaforge

on:
  push:
    branches: [ dev ]

env:
  CACHE_NUMBER: 1  # increase to reset cache manually


jobs:
  build-os-unix:
    strategy:
      matrix:
        os: [ "ubuntu-latest" , "macos-latest"]
        python-version: [ "3.7", "3.8", "3.9" ]

    name: ci-test+cache
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2  # checkout repository

      - name: Set cache date  # activate cache
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
#
      - name: Setup Mambaforge  # setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-test
          channel-priority: strict
          environment-file: environment.yml
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Update environment
        run: mamba env update -n env-test -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Lint with flake8
        run: |
          $CONDA/bin/conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
